baseURL: https://luanabassi.com.br/
languageCode: pt-br
defaultContentLanguage: pt
defaultContentLanguageInSubdir: false
title: My New Hugo Site
languages:
  pt:
    languageName: PortuguÃªs
    weight: 1
    contentDir: content
    params:
      description: My description
module:
  imports:
    - path: github.com/gethinode/hinode

